spring:
  application:
    name: naumen-tests-tgbot

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:tests_bot}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${pg_password:postgres}